#!/bin/bash

# Lấy ngày và giờ hiện tại
current_date=$(date)

# In ra phản hồi HTTP
echo "HTTP/1.1 200 OK"
echo "Connection: close"
echo "Date: $current_date"
echo "Server: netcat special deal"
echo "Content-Length: 274"
echo "Content-Type: text/html; charset=utf-8"
echo "Cache-Control: max-age=60"
echo
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "<title>Welcome to My Website</title>"
echo "</head>"
echo "<body>"
echo "<h1>Welcome to My Website</h1>"
echo "<p>This is a simple and valid HTML webpage generated by a bash script.</p>"
echo "<p>Current date is: $current_date</p>"
echo "</body>"
echo "</html>"
